version: "3"

services:
  rng:
    build: dockercoins/rng
    image: ${REGISTRY_SLASH-127.0.0.1:5000/}rng${COLON_TAG-:latest}
    deploy:
      mode: global

  hasher:
    build: dockercoins/hasher
    image: ${REGISTRY_SLASH-127.0.0.1:5000/}hasher${COLON_TAG-:latest}

  webui:
    build: dockercoins/webui
    image: ${REGISTRY_SLASH-127.0.0.1:5000/}webui${COLON_TAG-:latest}
    ports:
    - "8000:80"

  redis:
    image: redis

  worker:
    build: dockercoins/worker
    image: ${REGISTRY_SLASH-127.0.0.1:5000/}worker${COLON_TAG-:latest}
    deploy:
      replicas: 10

