---
- hosts: nodes
  sudo: true
  tasks:

    - name: installing dependencies
      apt:
        name: apt-transport-https,ca-certificates,python-pip
        state: present
        update_cache: true

    - name: fetching docker repo key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: adding package repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - deb http://http.debian.net/debian wheezy-backports main
        - deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename }} main

    - name: installing docker
      apt:
        name: docker-engine
        state: present
        update_cache: true

    - name: adding user vagrant to group docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: making docker daemon listen to port 55555
      lineinfile:
        dest: /etc/default/docker
        line: DOCKER_OPTS="--host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:55555"
        regexp: '^#?DOCKER_OPTS=.*$'
        state: present
      register: docker_opts

    - name: restarting docker daemon, if needed
      service:
        name: docker
        state: restarted
      when: docker_opts is defined and docker_opts.changed

    - name: performing pip autoupgrade
      pip:
        name: pip
        state: latest

    - name: installing virtualenv
      pip:
        name: virtualenv
        state: latest

    - name: creating docker-compose folder
      file:
        path: /opt/docker-compose
        state: directory
      register: docker_compose_folder

    - name: creating virtualenv for docker-compose
      shell: virtualenv /opt/docker-compose
      when: docker_compose_folder is defined and docker_compose_folder.changed

    - name: installing docker-compose
      pip:
        name: docker-compose
        state: latest
        virtualenv: /opt/docker-compose

    - name: making the docker-compose command available to user
      lineinfile:
        dest: .bashrc
        line: "alias docker-compose='/opt/docker-compose/bin/docker-compose'"
        state: present
        regexp: '^alias docker-compose=.*$'
